# Generated by Django 4.0.2 on 2022-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_registration_fathername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
