# Generated by Django 4.0.2 on 2022-06-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='admission_rate',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='fees_rate',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
