# Generated by Django 4.0.2 on 2022-06-07 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_accountnumber_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='net_due_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 17, 48, 57, 470510)),
        ),
    ]
