# Generated by Django 4.0.2 on 2022-06-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_payment_net_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='net_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
