# Generated by Django 4.0.2 on 2022-06-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_payment_net_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='reg_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
