# Generated by Django 4.0.2 on 2022-06-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_registration_reg_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='app.batch'),
        ),
    ]
