# Generated by Django 4.0.2 on 2022-06-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_registration_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='country',
            new_name='native_place',
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='height',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='status',
            field=models.CharField(default='0', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='weight',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
