# Generated by Django 4.0.2 on 2022-06-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_country_user_registration_native_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='select_status',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
