# Generated by Django 4.0.2 on 2022-06-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_user_registration_net_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='startdate',
        ),
        migrations.AlterField(
            model_name='category',
            name='cate_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machinenames', to='app.machine'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user_registration'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='app.workout'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userregistrationdesignation', to='app.designation'),
        ),
    ]
